### PR TITLE
[FlangClassic]: Fix a couple of warnings (port patches 12->13)   

### PR DESCRIPTION
**Pull request by nextsilicon-itay-bookstein**
Porting of https://github.com/flang-compiler/classic-flang-llvm-project/pull/61

### CODE REVIEW

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

-> Are these changes present in upstream llvm-project/clang main/release-13 branch?
-> Are the removed functions not present in upstream llvm-project/clang main/release-13 branch?

**Comment by nextsilicon-itay-bookstein** [comment]
As far as I can tell, all code modifications made in this PR's commits are made to code added by the non-upstreamed patch-list that classic-flag-llvm-project keeps migrating between stable LLVM releases.

**Comment by nextsilicon-itay-bookstein** [comment]
Ping :)

**Review by bryanpkc — APPROVED** [review]
LGTM

**Comment by bryanpkc** [comment]
Since this is just cherry-picking an approved patch from release_12x to release_13x, I will assume that @shivaramaarao continues to approve. 😄

**Comment by shivaramaarao** [comment]
Yes. it is fine with me.

**Pull request merged**
