### PR TITLE
Prepare llvm and clang for ARM64 build of Flang

### PR DESCRIPTION
**Pull request by michalpasztamobica**
Run Dockerfile script on a self-hosted ARM64 runner to prepare a docker image with llvm and clang built and installed for Flang to use when testing code.

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]

**Comment by michalpasztamobica** [comment]
This is essentially the same as https://github.com/flang-compiler/classic-flang-llvm-project/pull/39, but committed to `release_11x` branch (it is a bit odd that we have to keep copies of the jobs for them to tigger correctly, I guess github is focused on repos which have a clear `main`/`master` branch that holds these configs...)

The history is complicated because I was trying to make sure this will work correctly for `flang-compiler` by having this PR temporarily build on a PR. This is not possible due to an [issue with Github Actions](https://github.community/t/403-error-on-container-registry-push-from-github-action/173071/21). Fortunately the issue only affects building on PRs, while we really wanted to build on pushes to branch. We can be sure this will work, [as it already has worked for release_12x](https://github.com/flang-compiler/classic-flang-llvm-project/runs/2605087879?check_suite_focus=true) last night.

**Comment by michalpasztamobica** [comment]
Previous CI failure was due to ubuntu package repo sync... bad luck.
I force pushed to retrigger CI.

**Comment by michalpasztamobica** [comment]
The sync seems still in progress:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages.bz2  File has unexpected size (73402 != 73160). Mirror sync in progress? [IP: 104.42.185.173 443]
```
I'll try later...

**Comment by michalpasztamobica** [comment]
The original issue with CI has been removed, but apparently now the `apt update` requires `-y` option to accept some new gpg keys - hence the new commit with the CI fix.

**Comment by michalpasztamobica** [comment]
This is now passing CI and ready for final review @bryanpkc , @SouraVX , @kiranchandramohan .
Just a reminder - it is essentially a copy of what we already have on `release_12x` :smiley:

**Review by SouraVX — APPROVED** [review]

**Review by bryanpkc — APPROVED** [review]

**Pull request merged**
