### PR TITLE
 [DebugInfo] Removal of DIFortranArrayType and DIFortranSubrange

### PR DESCRIPTION
**Pull request by alokkrsharma**
These extensions are no more required after merge of below PR.
https://github.com/flang-compiler/classic-flang-llvm-project/pull/14

### CODE REVIEW

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by alokkrsharma** [comment]
> 
> 
> LGTM.

Thanks @bryanpkc .

**Comment by alokkrsharma** [comment]
Hi @kiranchandramohan  and @shivaramaarao is this PR good to be merged ?

**Comment by alokkrsharma** [comment]
Gentle reminder !!!

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

**Pull request merged**
