### PR TITLE
[DebugInfo] Enhance DIImportedEntity to accept children entities

### PR DESCRIPTION
**Pull request by alokkrsharma**
This is a backport from upstream/main to release_12x (cherry-pick) of below.

```
commit a5b72abc9eaadbd319f0fbb8ae947d2dd289b30a
Author: Alok Kumar Sharma <AlokKumar.Sharma@amd.com>
Date:   Tue Sep 7 11:25:44 2021 +0530
```

New field `elements` is added to '!DIImportedEntity', representing
list of aliased entities.
This is needed to dump optimized debugging information where all names
in a module are imported, but a few names are imported with overriding
aliases.

Reviewed By: dblaikie

Differential Revision: https://reviews.llvm.org/D109343

### CODE REVIEW

**Review by bryanpkc — APPROVED** [review]
LGTM

**Comment by bryanpkc** [comment]
Will you submit a PR for release_13x as well?

**Comment by alokkrsharma** [comment]
> Will you submit a PR for release_13x as well?

Raised https://github.com/flang-compiler/classic-flang-llvm-project/pull/93

**Comment by alokkrsharma** [comment]
@pawosm-arm can you please approve this ?

**Review by pawosm-arm — APPROVED** [review]

**Comment by pawosm-arm** [comment]
@alokkrsharma and @bryanpkc is there a plan for going with this commit (and any other commits like this one) to the mainline LLVM?

**Comment by alokkrsharma** [comment]
> @alokkrsharma and @bryanpkc is there a plan for going with this commit (and any other commits like this one) to the mainline LLVM?

I have already merged it there https://reviews.llvm.org/rGa5b72abc9eaadbd319f0fbb8ae947d2dd289b30a

**Pull request merged**
