### PR TITLE
Add ccache support to GitHub Actions

### PR DESCRIPTION
**Pull request by janisozaur**
This will likely spill over the default limit of 500MB, but would like to gather stats first.

### CODE REVIEW

**Comment by janisozaur** [comment]
Turns out that
1. The cache fits well below the default limit of 500MB -> it sits at roughly 150MB for Linux and macos
2. #18 is redundant, as the workflow file is taken from the PR branch already.

Once the current actions are finished and cache is uploaded I will submit another dummy commit to show the speedup, I expect great results.

**Comment by janisozaur** [comment]
|        | Time before | Time cached | Cache size |
|--------|-------------|-------------|------------|
| Ubuntu | 2h 11m      | 23m 16s     | 150MB      |
| macos  | 2h 18m      | 35m 32s     | 130MB      |

@bryanpkc done and done.

**Comment by michalpasztamobica** [comment]
@kiranchandramohan , @bryanpkc , I suggest we merge this next and cherry-pick to `release_11x` because (1) this is just a CI change, so we don't need all the approvals and (2) we will get an immense speed-up of the checks running in other PRs.

@janisozaur would you prefer to create a PR to `release_11x` yourself? This is where most development takes place right now.

**Comment by janisozaur** [comment]
@michalpasztamobica https://github.com/flang-compiler/classic-flang-llvm-project/pull/20

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by bryanpkc** [comment]
Can you please squash the commits? Or I can do it through the UI as well.

**Comment by janisozaur** [comment]
@bryanpkc please do - submitting squashed version would retrigger the CI

**Pull request merged**
