### PR TITLE
Port Classic Flang to LLVM 19.1.0

### PR DESCRIPTION
**Pull request by bryanpkc**
This pull request cherry-picks the Classic Flang patches from the `release_18x` branch, resolving a number of minor conflicts:

1. Upstream changes to `clang/include/clang/Driver/Options.td` that had been backported to `release_18x` were reverted, or reconciled with the new base branch.
2. Upstream Clang had dropped the option `-fno-fortran-main` in https://github.com/llvm/llvm-project/commit/8d5386669ed63548daf1bee415596582d6d78d7d. To resolve a merge conflict and to keep the code building without error, the option had been restored (but now guarded with the `ENABLE_CLASSIC_FLANG` macro).
3. Uses of `StringRef::equals` have been replaced with `StringRef::operator==`, `StringRef::endswith` with `StringRef::ends_with`, and `StringRef::startswith` with `StringRef::starts_with`. See https://github.com/llvm/llvm-project/commit/3fa409f2318ef790cc44836afe9a72830715ad84 and https://github.com/llvm/llvm-project/commit/4ec9a662d388db8a2bb862dbaa7fc3fd809d1240.
4. Uses of `Driver::InstalledDir` had been replaced with `Driver::Dir`. See https://github.com/llvm/llvm-project/commit/2b5cd8be3af43e5aa5b76b6aeb1edd3141b803ca.
5. The `#undef` directives in `llvm/include/llvm/Analysis/VecFuncs.def` had been moved into `llvm/lib/Analysis/TargetLibraryInfo.cpp` in https://github.com/llvm/llvm-project/commit/430729d71e4e582aa04b5d30796de14404fed56a.
6. A commit had been added after the port to fix up the FileCheck patterns in two test cases.

Workflow-related commits have already been pushed to [the `release_19x` branch](https://github.com/flang-compiler/classic-flang-llvm-project/commits/release_19x).

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]

**Comment by bryanpkc** [comment]
[The AArch64 build is failing](https://github.com/flang-compiler/classic-flang-llvm-project/actions/runs/11137793508/job/31202673247) due to CMake not finding `ZLIB`, even though [the container already has the `zlib1g-dev` package installed](https://github.com/flang-compiler/classic-flang-llvm-project/actions/runs/10923069716/job/30318814802).

**Comment by pawosm-arm** [comment]
> [The AArch64 build is failing](https://github.com/flang-compiler/classic-flang-llvm-project/actions/runs/11137793508/job/31202673247) due to CMake not finding `ZLIB`, even though [the container already has the `zlib1g-dev` package installed](https://github.com/flang-compiler/classic-flang-llvm-project/actions/runs/10923069716/job/30318814802).

What is the use of Zlib in LLVM? There's CMake option for not using it (and a separate option for not using ZSTD too)

**Comment by bryanpkc** [comment]
> What is the use of Zlib in LLVM? There's CMake option for not using it (and a separate option for not using ZSTD too)

Yes, I know. The problem here is that it isn't the LLVM build that breaks (because the zlib libraries and headers do exist), but the Flang build. We have never had to specify `LLVM_ENABLE_ZLIB` for CMake in the Flang build, so I suspect that something has changed with the CMake modules under `llvm/cmake/` in LLVM 19. I'm trying to understand why the behaviour has changed.

**Comment by bryanpkc** [comment]
I have fixed the AArch64 Docker container which was using an old version of CMake, causing the problem. See fa9105e4056f952e2668d471187fa94d767ff6f4.

**Comment by bryanpkc** [comment]
@shivaramaarao Could you review this PR?

**Review by shivaramaarao — APPROVED** [review]
Looks good to me. thanks for working on this.

**Pull request merged**
