### PR TITLE
[release_14x] Enhancements to CI script to allow Debug build

### PR DESCRIPTION
**Pull request by bryanpkc**
Cherry-pick #109 to the `release_14x` branch.

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]
Useful thing

**Comment by RichBarton-Arm** [comment]
As a CI change, this can be merged now with one approval right?

**Comment by RichBarton-Arm** [comment]
Also - check out the flang side of this here: https://github.com/flang-compiler/flang/pull/1251

**Comment by bryanpkc** [comment]
I agree with @RichBarton-Arm. I will merge this now, hoping that @shivaramaarao agrees too!

**Comment by RichBarton-Arm** [comment]
Thanks @bryanpkc  :-)

**Pull request merged**
