### PR TITLE
Port Classic Flang changes to LLVM 16

### PR DESCRIPTION
**Pull request by bryanpkc**

### CODE REVIEW

**Review by pawosm-arm — COMMENTED** [review]
I suppose the checks will stop failing after the classic flang part is merged.

**Comment by bryanpkc** [comment]
> I suppose the checks will stop failing after the classic flang part is merged.

Yes and no. The Flang test failures will be fixed by flang-compiler/flang#1380 and flang-compiler/flang#1381, but right now the CI jobs are failing during the OpenMP build. I wasn't able to reproduce this locally, and I'm still trying to figure out why the CI jobs are failing.

*Update: I have reproduced the problem.*

**Comment by bryanpkc** [comment]
Upstream `release/16.x` (llvm/llvm-project@7cbf1a2591520c2491aa35339f227775f4d3adf6) also fails with the same compile-time failure in OpenMP:
```
/home/b00375952/src/release_16x/openmp/libomptarget/plugins-nextgen/common/PluginInterface/PluginInterface.cpp:740:14: error: call to deleted constructor of 'llvm::Error'
      return Err;
             ^~~
/home/b00375952/src/release_16x/llvm/include/llvm/Support/Error.h:185:3: note: 'Error' has been explicitly marked deleted here
  Error(const Error &Other) = delete;
  ^
/home/b00375952/src/release_16x/llvm/include/llvm/Support/Error.h:492:18: note: passing argument to parameter 'Err' here
  Expected(Error Err)
                 ^
1 error generated.
```

The CMake command I used on Ubuntu 22.04 x86_64 was:
```sh
cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_COMPILER=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 \
      -DLLVM_TARGETS_TO_BUILD=X86 \
      -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
      -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_PROJECTS="clang;openmp" \
      ../llvm
```

*Update: This should now be fixed.*

**Review by pawosm-arm — APPROVED** [review]

**Review by shivaramaarao — APPROVED** [review]

**Comment by bryanpkc** [comment]
Added several libomptarget patches that should help with the `check-openmp` failures.

**Comment by bryanpkc** [comment]
Fixed a couple of test-related problems. All CI checks are passing now.

**Pull request merged**
