### PR TITLE
Backport 13.0.1 to release_13x

### PR DESCRIPTION
**Pull request by bryanpkc**
Update the branch with stability fixes from upstream.

### CODE REVIEW

**Comment by bryanpkc** [comment]
I'm not sure why GitHub complains that the branch cannot be rebased. It is already based on `release_13x` and should be mergeable as-is.

**Comment by bryanpkc** [comment]
We probably need to push these commits to the target branch by hand. According to the following discussion, there is no workaround for this GitHub limitation:

https://github.community/t/weird-problem-with-cannot-be-rebased-due-to-conflicts/178433

**Comment by pawosm-arm** [comment]
This is full of mainline LLVM project commits, what review policy shall we take on this?

**Comment by kiranchandramohan** [comment]
We will wave the review. @bryanpkc will merge this.

**Pull request merged**
