### PR TITLE
Enable ccache for GitHub Actions for release_11x

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by michalpasztamobica** [comment]
@kiranchandramohan , @bryanpkc , can we merge this CI improvement from @janisozaur soon, to get the other pending PRs build and test faster?

**Review by bryanpkc — APPROVED** [review]

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by bryanpkc** [comment]
As per discussion in the last call, we require only one external approval for CI. I'll merge this after tests are done.

**Comment by janisozaur** [comment]
@bryanpkc the CIs are green

**Pull request merged**
