### PR TITLE
CI fixes and llvm updates

### PR DESCRIPTION
**Pull request by michalpasztamobica**
This should fix the CI issue from https://github.com/flang-compiler/classic-flang-llvm-project/pull/14

@kiranchandramohan , FYI.

EDIT: A proper explanation of what this PR actually contains and accomplishes:
1) There was a bug that sneaked in unnoticed as neither us nor the CI has run the llvm and clang tests when adding `release_11x` branch. @bryanpkc fixed it in https://github.com/flang-compiler/classic-flang-llvm-project/pull/19 and I cherry-picked his commit.
2) The branch name in `llvm-project` was changed from `master` to `main` and we need to reflect this change in our repository, because we use `llvm-projects` actions to run regression tests. Instead of creating my own commit I cherry-picked https://github.com/llvm/llvm-project/commit/17e842f3785fe5f585f9adc0f6cacc431d327eee
3) I also got all the other commits from https://github.com/llvm/llvm-project/commits/release/11.x to fix other CI failures in `clang` and get our branch up to date with the origin's. I deliberately skipped the commits which modified workflows that we are not using,

### CODE REVIEW

**Comment by michalpasztamobica** [comment]
@kiranchandramohan , @alokkrsharma , seems like we are having some more issues with the CI, than just the branch rename from `master` to `main`. I will look at it and keep you posted in this PR.
@RichBarton-Arm , FYI.

**Comment by michalpasztamobica** [comment]
On Friday I tried cherry-picking all the commits from `llvm-project`'s `release/11.x` branch onto our `release_11x` branch. This improved the situation, but we still have 18 tests failing:
```
1 warning(s) in tests
Failed Tests (18):
  LLVM :: DebugInfo/AMDGPU/variable-locations.ll
  LLVM :: DebugInfo/BPF/extern-void.ll
  LLVM :: DebugInfo/Generic/debug-names-hash-collisions.ll
  LLVM :: DebugInfo/Generic/debug-names-index-type.ll
  LLVM :: DebugInfo/Generic/debug-names-linkage-name.ll
  LLVM :: DebugInfo/Generic/debug-names-many-cu.ll
  LLVM :: DebugInfo/Generic/debug-names-name-collisions.ll
  LLVM :: DebugInfo/Generic/debug-names-one-cu.ll
  LLVM :: DebugInfo/Generic/debug-names-two-cu.ll
  LLVM :: DebugInfo/Mips/dwarfdump-tls.ll
  LLVM :: DebugInfo/NVPTX/debug-addr-class.ll
  LLVM :: DebugInfo/X86/dwarf-callsite-related-attrs.ll
  LLVM :: DebugInfo/X86/dwarf-public-names.ll
  LLVM :: DebugInfo/X86/pr45181.ll
  LLVM :: DebugInfo/X86/stringpool.ll
  LLVM :: MC/WebAssembly/debug-info.ll
  LLVM :: MC/WebAssembly/dwarfdump.ll
  LLVM :: tools/llvm-dwarfdump/X86/statistics.ll

  Testing Time: 859.36s
  Unsupported      :  1104
  Passed           : 37222
  Expectedly Failed:   148
  Failed           :    18
```
I checked logs from our run and [the last run in llvm-project repository](https://github.com/llvm/llvm-project/runs/1826144966?check_suite_focus=true), but I see no differences in the environment. We do have two tests more, but they might be coming from the extra commits we have added to the project in flang repo. 

I will try to reproduce the failures locally - if they are there, I will try to figure out if they are caused by one of our extra commits. If they do not reproduce, I will keep searching the configs - after all, the CI started failing just because of the changes in how the project is building with Github Actions.

**Comment by michalpasztamobica** [comment]
Building without flang-specific commits cherry-picked from `release_110` fixes the issue, but the tests that are failing have not been added recently. I am trying to track down the exact commit which breaks the tests and figure out the root cause.

**Comment by michalpasztamobica** [comment]
After checking many different aspects of the situation I must ask for help, @bryanpkc .

Right now on every PR we are running the llvm's test suite (after building we call `make check-all`) which means we are running tens of thousands of clang/llvm tests on every PR. When adding the `release_11x` we have not really run this suite, because it only trigger when `./clang` or `./llvm` paths are touched by the changes.

So we had these failures from the beginning of `release_11x` lifetime, but we did not see them as I only checked if `classic-flang-llvm-project` builds and if `flang`'s tests are passing fine.

I checked that the failures are mostly caused by https://github.com/michalpasztamobica/classic-flang-llvm-project/commit/82b38d24a51871a210a184dd558e9b955a421e8e, but this commit is a base of a few subsequent ones.

So it seems we should revisit those changes and their influence on the test failures. 

@bryanpkc , as you have previously added the changes from `release_90` onto `release_100`, perhaps you'd be able to take a look at the current failures and decide if they are relevant or if we should just ignore those failures with `; UNSUPPORTED classic_flang` as was done with some tests in `release_100`. Your advice would here would be much appreciated.

**Comment by bryanpkc** [comment]
@michalpasztamobica Let me take a look and get back to you.

**Comment by bryanpkc** [comment]
@michalpasztamobica PR #19 fixed the test failures for me. I only built the X86 and AArch64 backends so I didn't see the AMDGPU, BPF, and WebAssembly errors. I hope we are lucky and this patch fixes everything!

**Comment by michalpasztamobica** [comment]
@kiranchandramohan , @bryanpkc , this is all green and can be merged to unblock other PRs.

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by kiranchandramohan** [comment]
Should we squash or is rebase and merge sufficient? @michalpasztamobica

**Comment by michalpasztamobica** [comment]
I wouldn't squash - we have better visibility of what was picked from where if we leave it as is. 
We may want to cherry-pick again if new commits show up on https://github.com/llvm/llvm-project/tree/release/11.x

**Comment by kiranchandramohan** [comment]
As per discussion in the last call, we require only one external approval for CI.

**Pull request merged**
