### PR TITLE
[DebugInfo] Support of `-gpubnames` in Driver

### PR DESCRIPTION
**Pull request by SouraVX**
Flang side changes:
https://github.com/flang-compiler/flang/pull/1033

### CODE REVIEW

**Comment by SouraVX** [comment]
Sequence of applying/testing/validating:
Steps:
1. Apply this one and initiate build & installation of flang-driver
2. Apply https://github.com/flang-compiler/flang/pull/1033 and initiate the build & installation of flang.
3. `make check-flang` should pass. (Passing locally, following above sequence :) )

**Comment by SouraVX** [comment]
@michalpasztamobica  this one also needs a rebase ?

**Comment by michalpasztamobica** [comment]
@SouraVX , no, this one doesn't need rebase.

**Review by michalpasztamobica — APPROVED** [review]
CI is passing, so fine with me, but I suggest you wait for other more competent reviewers to evaluate the influence on the llvm itself :)

**Review by kiranchandramohan — APPROVED** [review]
Please do the following also,
1) add a driver test.
2) Add a patch for release 12 and 10.

**Comment by SouraVX** [comment]
> Please do the following also,
> 
> 1. add a driver test.
> 2. Add a patch for release 12 and 10.

Not sure about the testing the Driver part, let me have a look. Is there any precedent in past ?

**Comment by kiranchandramohan** [comment]
> > Please do the following also,
> > 
> > 1. add a driver test.
> > 2. Add a patch for release 12 and 10.
> 
> Not sure about the testing the Driver part, let me have a look. Is there any precedent in past ?

If there are no existing tests then you may skip. I was probably going by our downstream compiler where have tests for any new flag that we add.

**Comment by bryanpkc** [comment]
> Not sure about the testing the Driver part, let me have a look. Is there any precedent in past ?

Apologies for the late reply. There are tests in `clang/test/Driver/flang`.

**Comment by kiranchandramohan** [comment]
@bryanpkc I didn't see any for the -x flags. I see tests for named flags. But i agree it will be good to have tests so that we do not lose these flags when we move to new llvm versions.

**Comment by bryanpkc** [comment]
Yes, I agree. It will also help catch cases when a downstream modification conflicts with an upstream use of a -x flag.

**Pull request merged**
