### PR TITLE
Port Classic Flang to LLVM 15

### PR DESCRIPTION
**Pull request by bryanpkc**
This PR rebases all downstream patches from the `release_14x` branch on to [llvmorg-15.0.0](https://github.com/flang-compiler/classic-flang-llvm-project/commit/4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137).

### CODE REVIEW

**Comment by bryanpkc** [comment]
A newly introduced test case ([openmp/runtime/test/ompt/teams/distribute_dispatch.c](https://github.com/flang-compiler/classic-flang-llvm-project/blob/release_15x/openmp/runtime/test/ompt/teams/distribute_dispatch.c)) is failing, [possibly due to lack of threads on the GitHub runner](https://github.com/flang-compiler/classic-flang-llvm-project/runs/8236605249?check_suite_focus=true#step:8:19777):
```
# command stderr:
OMP: Warning #96: Cannot form a team with 4 threads, using 2 instead.
OMP: Hint Consider unsetting KMP_DEVICE_THREAD_LIMIT (KMP_ALL_THREADS), KMP_TEAMS_THREAD_LIMIT, and OMP_THREAD_LIMIT (if any are set).
```
The FileCheck patterns in the test clearly expect four threads to be running.

This test is unrelated to any of the Classic Flang changes I made in this PR. The upstream GitHub actions do not test OpenMP functionality, so they are not affected. I am going to mark the test as `UNSUPPORTED` for now.

**Review by pawosm-arm — APPROVED** [review]
I assume this needs to be merged first, before flang issues could be addressed.

**Comment by bryanpkc** [comment]
It is the other way around. The Flang PRs need to be merged before the CI can run successfully on this PR.

**Comment by bryanpkc** [comment]
All CI tests have passed. It would be nice if more reviewers could have a look at this PR. Since GitHub thinks this PR is too large (even though there is zero merge conflict with the target branch), once I get enough approvals, I will directly push the patches on to the target branch (`release_15x`). Thanks.

**Comment by bryanpkc** [comment]
gentle ping @RichBarton-Arm @shivaramaarao @SouraVX

**Comment by bryanpkc** [comment]
Rebased the branch on [llvmorg-15.0.3](https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.3) and added a patch to enable AArch64 test jobs on PRs.

**Comment by bryanpkc** [comment]
Last call for reviews...

**Pull request merged**
