### PR TITLE
Removing CI test-base for release_100 (release_100).

### PR DESCRIPTION
**Pull request by abrahamtovarmob**
This PR depends on https://github.com/flang-compiler/flang/pull/1133

### CODE REVIEW

**Comment by bryanpkc** [comment]
I don't think this is necessary. Why don't we just leave it alone, in case we build the `release_100` branch for some reason in the future?

**Comment by bryanpkc** [comment]
I think you should remove the trigger in `.github/workflows/flang-tests.yml` instead.

**Comment by abrahamtovarmob** [comment]
Moved the change from the build to the test file

**Review by michalpasztamobica — APPROVED** [review]
This looks good to me :)

**Review by bryanpkc — APPROVED** [review]

**Pull request merged**
